Problem: `error C1090: PDB API call failed, error code '12'`
Solution: upgrade to C++20

NB: for more information, see: https://stackoverflow.com/questions/79729921