Revert "Make the build server check the net dimensions"
This reverts commit ceae6e87d1d3788163673904a2cf9cb11c85befa.

Rationale: got "fatal error C1060: compiler is out of heap space" on AppVeyor.